services:
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=MASTER_KEY
    volumes:
      - ./meili_data:/meili_data

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - '2500:2500'
      - '9000:9000'
